// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygLx0mvgODnIRGHdbWqAamQFj4oYx7ro',
    appId: '1:186912980635:web:a43b57116c3e14acfd903e',
    messagingSenderId: '186912980635',
    projectId: 'chatapp-d55aa',
    authDomain: 'chatapp-d55aa.firebaseapp.com',
    storageBucket: 'chatapp-d55aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFiYvXcWa3BLYvTKsH9T2u0bxeUz25do',
    appId: '1:186912980635:android:f85440161de5d559fd903e',
    messagingSenderId: '186912980635',
    projectId: 'chatapp-d55aa',
    storageBucket: 'chatapp-d55aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1i21t0V_4UVz7TAqt6G_GAEuu_x9yRo',
    appId: '1:186912980635:ios:ad6e58374a1502f4fd903e',
    messagingSenderId: '186912980635',
    projectId: 'chatapp-d55aa',
    storageBucket: 'chatapp-d55aa.appspot.com',
    iosBundleId: 'com.tal.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg1i21t0V_4UVz7TAqt6G_GAEuu_x9yRo',
    appId: '1:186912980635:ios:ad6e58374a1502f4fd903e',
    messagingSenderId: '186912980635',
    projectId: 'chatapp-d55aa',
    storageBucket: 'chatapp-d55aa.appspot.com',
    iosBundleId: 'com.tal.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDygLx0mvgODnIRGHdbWqAamQFj4oYx7ro',
    appId: '1:186912980635:web:8f358f943a97e22ffd903e',
    messagingSenderId: '186912980635',
    projectId: 'chatapp-d55aa',
    authDomain: 'chatapp-d55aa.firebaseapp.com',
    storageBucket: 'chatapp-d55aa.appspot.com',
  );
}
